### ISSUE TITLE
Split posteriordb and the interface packages

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/posteriordb#189]
Would it be a good idea to split the database and the interface code to independent repos?

Then database part could gather the models and have tests that everything are as they should, and interfaces could create their own tests and run them when the interface part is changed.

**Comment by MansMeg** [comment]
I do not understand completely. What do you mean with the interface code? You mean testing to run say a TensorFlow Probability model?

**Comment by ahartikainen** [comment]
R package and python package would be their own repos.

**Comment by MansMeg** [comment]
Yes, that would probably be a good idea further on, yes indeed.

**Comment by MansMeg** [comment]
Now this has been fixed.
