### ISSUE TITLE
address JSON format issues

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/posteriordb#208]
while I appreciate the use of JSON as a data format, there are a few concerns:

- ~for large input datasets which are essentially tabular in shape, JSON is a very verbose format.~

- JSON doesn't have enough structure for arrays and matrices:
   - cannot represent an empty N-dim array in JSON - all empty arrays are "[ ]"
  - doesn't care about array shape

- concepts of NaN, neg inf, inf, and missing data have varying representations across different platforms and libraries.

suggestions:

- make explicit allowed encodings for NaN and friends
- ~for strictly tabular datasets, allow CSV file format as well~

- for multi-dim numeric data, allow appropriate encoding

update:  CSV and tabular data is not that relevant for the kinds of data needed for posteriordb models - striking this point.

**Comment by MansMeg** [comment]
I agree with you about the problems. I just find it to be the least bad alternative. The problem you point to is good to address. I have actually had this as a problem with the covid19 model. Although, I cant come up with a better alternative. The focus has been on making the use as simple as possible.

Regarding your suggestions:
1) I agree. this should have been done long ago.
2) The problem with CSV is that it will not allow any nesting so it would only work for one simple matrix? Adding that will most likely increase the maintenance burden and reduce the simplicity of use. I would like to avoid this. Is there any benefit except verbose of storing like this?
3) I do not really understand what you mean? A specific encoding for dimensions?

Thanks!

**Comment by mitzimorris** [comment]
for #3, I was more thinking about other encoding formats - NetCDF?  (never used it myself - it's what Arviz is using)

for #2, not a fan of CSV by any means,  and the more formats supported, the greater the maintenance burden. 
but for the benchmarking project, big models require big data - for large regression datasets, if the data already exists in CSV format, then it would be better to offer conversion in a way that is known and controlled instead of putting this burden on the submitter.

**Comment by mitzimorris** [comment]
actually, take that back - JSON format for data is good for CmdStan, so JSON is the only appropriate choice for input data.

JSON format defined here:  https://mc-stan.org/docs/2_25/cmdstan-guide/json.html

**Comment by ahartikainen** [comment]
I would suggest that every json should have also metadata for variable dimensions and datatype (int vs float).

I think there are ways to circumvent nan and inf issues.

Also, every json should be explicitly be encoded in utf-8 or utf-16.

**Comment by mitzimorris** [comment]
most JSON libraries can handle "nan", "inf", "+inf", and "-inf", but documentation should be explicit on strings and interpretation.

+1 for metadata - note the JSON doesn't differentiate between int and float - need metadata for both numeric type as well as array shape.

**Comment by MansMeg** [comment]
Alright. So we have converged toward JSON as an independent format for Stan data with these additions. Should we just add these things and create a JSON schema for this? Or are there already JSON formats that would solve this for us with known schemas?

**Comment by MansMeg** [comment]
So the question is how we continue with this JSON issue? I guess we would like to use just one format. I could just run everything through the `write_stan_json()`. Would that solve your issue @mitzimorris ? or should we add the metadata as well first?

**Comment by ahartikainen** [comment]
Does R force the encoding or is it using the system defaults?

**Comment by mitzimorris** [comment]
> The only issue with dimensions is representing a 0xN matrix or 2D array or any 0xNx...xM K-dimensional array.

we ran into an issue with input data which empty multi-dim arrays -  we had to hack Stan's `var_context` reader to address this - https://github.com/stan-dev/stan/issues/2867

don't know if this is a concern for posteriordb - perhaps?

**Comment by jgabry** [comment]
> don't know if this is a concern for posteriordb - perhaps?

Maybe not much of a concern. I don't think it's necessary for posteriordb to have models that use empty data arrays (I can't think of a case where that's essential for what posteriordb is intended for). But I could be wrong!

**Comment by MansMeg** [comment]
I think I have run into the problem of the difference between a 1*1*1 array and an ordinary scalar in R for some model, but I do not remember how I solved that.

I suggest that I, for now, add that the JSON files should be in UTF-8 format and that we open up to have an ```__info``` slot to define specific information if that comes up further down the line. Does that sound like a solution for now?

**Comment by ahartikainen** [comment]
Sounds good.

**Comment by MansMeg** [comment]
I think everyone agreed to the proposed solution so I close this for now.
