### ISSUE TITLE
`gh` package required

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/posteriordb#220]
I tried to use the package without `gh` installed and got:

```
> pd <- pdb_default()
Error in loadNamespace(name) : there is no package called ‘gh’
```

I see it's in the suggests package list. Should this package be required (so it gets automatically installed)?

**Comment by MansMeg** [comment]
Hi!

I think the main idea from the beginning was that it would only be used if we used github. Now I realize, github is the default. So yes, you are right. We should move this so it is installed automatically.

**Comment by MansMeg** [comment]
This has now been fixed.
