### ISSUE TITLE
Transferring to stan-dev

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/posteriordb#223]
Now that posteriordb has been accepted to the `stan-dev` organization we will proceed with transferring this repository.

I am creating an issue so we do this transparently and that we have somewhere to have a checklist. 

The transfer will be done on Thursday at some point soon after 1pm (13) CET. Make sure to not push to this repository after noon on Thursday as it may get lost (it most likely wont be, but just in case). Once this issue is closed, proceed with working with posteriordb as usual.

Pre-transfer:
- [x] make @rok-cesnovar  an admin of posteriordb so there will be no permission issues on transfer. I am now a member, just need elevated permissions. (assigned to @MansMeg)
- [x] make Måns a member of stan-dev
- [x] make a local backup of posteriordb after 1pm CET on Thursday with the latest state of the repository (this is very likely to be unnecessary as transferring a repository should be trivial, but lets play it safe) (assigned to @MansMeg)
- [x] check which users have write permissions to this repo pre-tranfer (assigned to @rok-cesnovar)

(Ari Hartikainen, ahartikainen • Collaborator)
(Aki Vehtari, avehtari • Collaborator)
(Eero Linna, eerolinna • Collaborator)
(Paul-Christian Bürkner, paul-buerkner • Collaborator)
(jarnefeltoliver, Collaborator)
+ Rok and Måns

- [x] Do the transfer

Post-transfer:
- [x] Check that @MansMeg has admin permissions on the transferred repository and other users with elevated permissions have them post-transfer as well 
- [x] Fix hard-coded URLs in Readme.md and the rest of the repository (for example `remotes::install_github("MansMeg/posteriordb", subdir = "rpackage")`) (assigned to @MansMeg). 
- [x] Make sure `remotes::install_github("stan-dev/posteriordb", subdir = "rpackage")` works (assigned to @rok-cesnovar)
- [x] Check that codecov works as expected post transfer. May require changing URLs in codecov. Also check Github Actions but that should not be a problem. (assigned to @rok-cesnovar and @MansMeg )
- [x] Check that open issues are still in place (assigned to @rok-cesnovar)

**Comment by MansMeg** [comment]
I close it for now since github action is working and Python pass. Seem to be an issue with R but that is another issue.
