### ISSUE TITLE
install instructions for R package

### ISSUE THREAD

**Issue by jsocolar** [stan-dev/posteriordb#235]
Currently the rpackage/README.rmd has
```
remotes::install_github("MansMeg/posteriordb", subdir = "rpackage/")
```
This fails for me (R 4.0.2 on Mojave and 4.0.5 on Big Sur) in a sort of weird way.  If I do not have a previous installation of `posteriordb`, then this errors with
```
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`MansMeg`) and repo name (`posteriordb`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.
```
If I delete the trailing slash on `rpackage/`, then it installs fine.  Confusingly, if I then add the trailing slash back and do
```
remotes::install_github("MansMeg/posteriordb", subdir = "rpackage/", force = TRUE)
```
everything works.  So it seems the slash is a problem, but only if I lack a previous install.  No idea what that's about.

Suggested fix is deleting the slash.

Additionally, I presume it would be appropriate to change `MansMeg/posteriordb` to `stan-dev/posteriordb`?

**Comment by MansMeg** [comment]
Thanks! Ill fix!

**Comment by jsocolar** [comment]
I can install from stan-dev right now, and it seems to work?

**Comment by MansMeg** [comment]
Yes. It should work.

**Comment by MansMeg** [comment]
Now this should been fixed! Thanks!
