### ISSUE TITLE
PyMC3 eight school example

### ISSUE THREAD

**Issue by xidulu** [stan-dev/posteriordb#247]
`tau`, the scale parameter should lie on the positive real value space therefore it should be HalfCauchy or be transformed through exponential function?

https://github.com/stan-dev/posteriordb/blob/master/posterior_database/models/pymc3/eight_schools_noncentered.py#L14

**Comment by MansMeg** [comment]
Yes. You are right. Im not very good with pymc3. If you can add a PR that would be great. 

I think you should use exp since that is what stan is doing and then we can check that we get the same log density for models both in pymc3 and stan.

**Comment by xidulu** [comment]
@MansMeg
Happy to open a PR to fix it, but I am not sure how to check the equivalence of log_density, could you provide some instruction on it?

Thanks

**Comment by xidulu** [comment]
@MansMeg 
Thanks! I will have a look

**Comment by MansMeg** [comment]
Hi!

I close this issue for now. Just reopen it if you have further questions.
