### ISSUE TITLE
Missing reference posteriors

### ISSUE THREAD

**Issue by pipme** [stan-dev/posteriordb#249]
Hi,

There are 79 missing reference posteriors/draws out of 128 total number of posteriors, if I'm not mistaken.

Could you explain a bit why they are missing? Is it due to some difficulties when doing MCMC or something else? I saw a [comment ](https://github.com/stan-dev/posteriordb/issues/164#issuecomment-616990201) but not sure why there is such a large number of posteriors without reference MCMC samples.

Thanks.

**Comment by MansMeg** [comment]
Hi!

There are multiple reasons for this.
1) Some models are new, and I will compute new posteriors for them. But there are currently additional models in a PR, so I will compute the reference draws when they are merged.
2) Some models are essentially (at least in practice) impossible to generate with Stan, such as highly multimodal distributions as the LDA models. The goal is to flag these models as "very difficult".
3) Some posteriors have so many parameters (such as the ovarian model) that storing the posterior would be practically impossible on GitHub. The goal is to flag this as well and give a setting on how to compute the posterior yourself. I know the ovarian posterior was computed in the pathfinder paper [here](https://arxiv.org/abs/2108.03782). 

If you compute a posterior reference draw yourself - feel free to do a PR!

**Comment by pipme** [comment]
Ok, thanks for the clarification!
