### ISSUE TITLE
Make a new release?

### ISSUE THREAD

**Issue by sethaxen** [stan-dev/posteriordb#250]
Last month the version number was bumped to v0.3, but still the most recent GitHub release is for v0.2.0. Would it make sense to make a new GitHub release? This generates assets that can be downloaded via https without fussing around with the GitHub API.

**Comment by MansMeg** [comment]
Yes. We have a 0.4 that is waiting review. As soon as that is done Ill do a github release for 0.4.0.

**Comment by MansMeg** [comment]
Done!

**Comment by sethaxen** [comment]
Thanks!
