### ISSUE TITLE
Add a graph over the database in the README

### ISSUE THREAD

**Issue by MansMeg** [stan-dev/posteriordb#40]
We need to have a graph of the data base (need to add it to the README) to simply explain the database and how it looks Steve may have ideas here.

**Comment by eerolinna** [comment]
Do you mean a graph of the folder structure? Or a graph of the available models and datasets?

**Comment by MansMeg** [comment]
It was a comment by Steven. He would like to have a graph over the relationships in the posterior database. How is stuff related etc.

**Comment by MansMeg** [comment]
This has more or less been fixed now.
