### ISSUE TITLE
Add CI check for generated README

### ISSUE THREAD

**Issue by eerolinna** [stan-dev/posteriordb#65]
It would be good to make sure in CI that the generated README is up-to-date. So essentially test that
```R
read.file("README.md") == generate_from_Rmd("README.Rmd")
```
where `generate_from_Rmd` would be a function that generates markdown file from R-markdown file (I guess a function like this might exist already but I don't know the real name)

**Comment by MansMeg** [comment]
This is the function to render the rmd file:
rmarkdown::render("README.rmd", "README.md")

**Comment by MansMeg** [comment]
Now this has been fixed for the R package.
